# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/83a15545-00ed-4d6c-8414-eb18ba2d8eea";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3099-64DA";
      fsType = "vfat";
    };

  fileSystems."/mnt/diskp" =
    { device = "/dev/disk/by-uuid/29b42662-9122-4653-a0d7-517b30930ce3";
      fsType = "ext4";
    };

  fileSystems."/mnt/disks/disk0" =
    { device = "/dev/disk/by-uuid/941f248e-8a70-4d00-a0eb-dc52c8d47fe4";
      fsType = "ext4";
    };

  fileSystems."/mnt/disks/disk1" =
    { device = "/dev/disk/by-uuid/d57774de-b3d2-4880-adfb-bcc1ae4db2f2";
      fsType = "ext4";
    };

  fileSystems."/mnt/disks/disk2" =
    { device = "/dev/disk/by-uuid/45fdb83e-5673-44e4-8800-86c7001b9635";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a1e4aacc-0564-40bc-bb2e-9767f641371e"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
